# docker compose example
services:
  caddy:
    pull_policy: always
    image: public.ecr.aws/sliamb/caddy:latest
    container_name: caddy
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - DNS=223.5.5.5,8.8.8.8
    volumes:
      - ./config:/config
    network_mode: "host"
    # Use mapping if not using host network_mode.
    # ports:
    #   - "80:80"
    #   - "443:443"